[package]
name = "wal"
version = "0.1.0"
authors = ["Dan Burkert <dan@danburkert.com>"]

[dependencies]
byteorder = "*"
crc = "*"
memmap = "*"
rand = "*"
eventual = "*"
log = "*"

[dev-dependencies]
docopt = "*"
histogram = { git = "https://github.com/brayniac/histogram" }
regex = "*"
rustc-serialize = "*"
tempdir = "*"
time = "*"
